const AppConstants = {
    roleIds: {
        bundelingSp: 6,
        operator: 5,
        toolShop: 3,
        QA: 4,
        PPC:2,
        admin: 1
    },
    workFlowIds:{
        PPCInprogress : 2,
        PPCHold : 3,
        Queued_for_Tool_Shop: 4,
        ToolShopInprogress: 5,
        ToolShopHold: 6,
        QueuedforQA: 7,
        QAInprogress: 8,
        QAHold: 9,
        QueuedforOperator_Entry: 10,
        OperatorEntryInprogress: 11,
        OperatorEntryHold: 12,
        QueuedforBundlingSupervisior: 13,
        BundlingSupervisiorInprogress: 14,
        BundlingSupervisiorHold: 15,
        BundlingSupervisiorCompleted: 16
    },
    pending: "pending",
    sectionNo: "Section No",
    viewDetails: "View Details",
    poNo: "PO No",
    customerName: "Customer Name",
    dataFromPPC: "Data from PPC",
    toolShopData: "Tool Shop Data",
    qaEntry: "QA Entry",
    dataFromOperatorEntry: "Data from Operator Entry",
    dataFromBundlingSupervisor: "Data from Bunldling Supervisor",
    die: "DIE",
    noOfCavity: "No. of Cavity",
    bolsterEntry: "Bolster Entry",
    backerEntry: "Backer Entry",
    specialBackerEntry: "Special Backer Entry",
    ringEntry: "Ring Entry",
    dieSetter: "Die Setter",
    weldingChamber: "Welding Chamber",
    batchNo: "Batch No.",
    buttWeightKg: "Butt Weight (Kgs)",
    pushOnBilletLength: "Push On Billet Length",
    approxPushQty: "Approx Push Qty (Kg)",
    startTime: "Start Time",
    endTime: "End Time",
    processTime: "Process Time",
    productionRateActual: "Production Rate Actual",
    dieWithAluminium: "Die With Aluminium",
    dieFailed: "Die Failed ",
    dieFailureReason: "Die Failure Reason",
    breakdownStartTime: "Breakdown Start Time",
    breakdownEndTime: "Breakdown End Time",
    reasonForBreakdown: "Reason For Breakdown",
    timeTakenBreakdown: "Time Taken Breakdown",
    previousDayDieContinue: "Previous Day Die Continue",
    nameOfOperator: "Name Of Operator",
    finishQuantity: "Finish Quantity",
    noOfPcsPerBundle: "No of Pcs Per Bundle",
    bundleWeightKg: "Bundle Weight (Kg)",
    noOfBundles: "No. of Bundles",
    correctionQty: "Correction Qty",
    totalNoOfPcs: "Total No. of Pcs",
    totalFinishQty: "Total Finish Qty",
    recovery: "Recovery",
    logEndCutScrapInch: "Log End Cut Scrap (Inch)",
    logEndCutScrapWeight: "Log End Cut Scrap (Weight)",
    salesOrderNo: "Sales Order No",
    allowTemper: "Alloy Temper",
    poTotalQuantity: "Po Total Quantity",
    extrudedQuantity: "Extruded Quantity (Kgs)",
    balancePOQuantity: "Balance PO Quantity",
    cutLengthTolerance: "Cut Length Tolerance (mm)",
    quantityTolerance: "Quantity Tolerance (%)",
    marketingRemarks: "Marketing remarks",
    cutLength: "Cut Length",
    priorityAssignment: "Priority Assignment",
    plannedQuantity: "Planned Quantity (Kgs)",
    plannedNoOfBillets: "Planned No. of Billet and Billet Length(Inches)",
    prodRateReq: "Production Rate Req (Kg/Hr)",
    plannedFrontEndCoringLength: "Planned FrontEnd Coring Length (mm)",
    plannedBackEndCoringLength: "Planned BackEnd Coring Length (mm)",
    plannedExtrusionLength: "Planned Extrusion Length",
    cutBillet: "Cut Billets",
    ppcRemarks: "PPC Remarks",

    PENDING: "PENDING",
    INPROGRESS: "INPROGRESS",
    HOLD: "HOLD",
    PICK: "PICK",
    COMPLETED: "COMPLETED",
    SECRET_KEY: "d#@%[q*=)r3v0Lit3sEcRet(=$@-!+#b",

    Die: "Die",
    Plant: "Plant",
    DieFailureReason: "Die Failure Reason",
    ReasonForBreakDown: "Reason For Break Down",
    ResponsibleDepartmentForBreakdown: "Responsible Department For Breakdown",
    ProcessStage: "ProcessStage",

    //for ppcDate
        plantSelected: "Plant Selected",
        pressAllocation: "Press Allocation",
        plannedQty: "Planned Quantity (Kgs)",
        plannedInternalAlloy: "Planned Internal Alloy",
        plannedNoOfBilletAndLength: "Planned No. of Billet and Billet Length (Inches)",
        productionRateRequired: "Production Rate Req (Kg/Hr)",
        plannedQuenching: "Planned Quenching",
        frontEndCoringLength: "Planned Front End Coring Length (mm)",
        backEndCoringLength: "Planned Back End Coring Length (mm)",
        plantExtrusionLength:"Planned Extrusion Length",
        plannedButtThickness: "Planned Butt Thickness (Inches)",
        cutBillets: "Cut Billets",
        buttWeightPerInch: "Butt Weight Per Inch",
        priorityAssignmentRefId: "Priority Assignment",
        remarks: "PPC Remarks",
        cutlengthtolerancelower:"Cut Length Tolerance Lower (mm)",
        cutlengthtoleranceupper:"Cut Length Tolerance Upper (mm)",
        qaremarks:"QA Remarks",

    //operatorentry
    DieTrial: "Die Trial",
    DieWithAluminium: "Die With Aluminium",
    PreviousDayDieContinue: "Previous Day Die Continue",
    BatchNo: "Batch No",
    ActualInternalAlloy: "Actual Internal Alloy",
    StartTime: "Start Time",
    EndTime: "End Time",
    ProcessTime: "Process Time,",
    NoofBilletandBilletLength: "No. of Billet and Billet Length",
    ActualButtthickness: "Actual Butt thickness (inch)",
    Breakthroughpressure: "Breakthrough pressure",
    PushOnBilletLength: "Push On Billet Length",
    PushQty: "Push Qty (Kgs)",
    ActualProductionRate: "Actual Production Rate",
    ButtWeight: "Butt Weight (Kgs)",
    DieFail: "Die Fail",
    Breakdownduration: "Breakdown duration(mins)",
    Logendscraplength: "Log end scrap length(mm)",
    LogendScrap: "Log end Scrap (kgs)",
    OperatorName: "Operator Name",
    BreakDown: "Break Down",
    BreakdownStart1Time: "Breakdown Start1 Time",
    Breakdown1EndTime: "Breakdown End Time",
    ReasonForBreakdown: "Reason For Breakdown",
    ResponsibleDepartmentforBreakdown: "Responsible Department for Breakdown",


    login: {
        email: "Enter Email Id",
        password: "Enter Password"
    },
    newPassword:"New Password",
    confirmPassword: "Confirm Password",
    prev: "Prev",
    next: "Next"
}

export default AppConstants;